set_property PACKAGE_PIN T5 [get_ports clk]
set_property PACKAGE_PIN R15 [get_ports stop]
set_property PACKAGE_PIN K2 [get_ports led1]
set_property PACKAGE_PIN J2 [get_ports led2]
set_property PACKAGE_PIN B4 [get_ports {digit_num[6]}]
set_property PACKAGE_PIN A4 [get_ports {digit_num[5]}]
set_property PACKAGE_PIN A3 [get_ports {digit_num[4]}]
set_property PACKAGE_PIN B1 [get_ports {digit_num[3]}]
set_property PACKAGE_PIN A1 [get_ports {digit_num[2]}]
set_property PACKAGE_PIN B3 [get_ports {digit_num[1]}]
set_property PACKAGE_PIN B2 [get_ports {digit_num[0]}]
set_property PACKAGE_PIN D5 [get_ports {digit_num[7]}]
set_property PACKAGE_PIN H1 [get_ports {select_digit[3]}]
set_property PACKAGE_PIN C1 [get_ports {select_digit[2]}]
set_property PACKAGE_PIN C2 [get_ports {select_digit[1]}]
set_property PACKAGE_PIN G2 [get_ports {select_digit[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {digit_num[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_num[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_num[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_num[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_num[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_num[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_num[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_num[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {select_digit[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {select_digit[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {select_digit[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {select_digit[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports led1]
set_property IOSTANDARD LVCMOS33 [get_ports led2]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports run]
set_property IOSTANDARD LVCMOS33 [get_ports stop]

set_property PACKAGE_PIN P15 [get_ports reset]
set_property PACKAGE_PIN V1 [get_ports run]


set_property IOSTANDARD LVCMOS33 [get_ports speaker]
set_property PACKAGE_PIN G13 [get_ports speaker]
